### PR TITLE
adding initial files, index.html

### PR DESCRIPTION
**Pull request by Thomaswaters05**

### CODE REVIEW

**Comment by copypastedeveloper** [comment]
@Thomaswaters05 is this ready to go?

**Comment by Thomaswaters05** [comment]
Not quite yet- I am trying to get everything speaking/working properly. About 85% done and hoping to be completed by tomorrow.

**Comment by copypastedeveloper** [comment]
Cool.

**Comment by Thomaswaters05** [comment]
Ready for review- I have one grunt error that I attempted to put in my gruntfile globals{} but did not seem to take the error away. Other than that all grunt errors have been taken care of.

**Comment by zoeames** [comment]
looks great!  i fixed that one grunt error by putting your iife name in the Gruntfile.js 👍

**Comment by Thomaswaters05** [comment]
Fantastic!! Merging now- Thank you Zoe!

**Pull request merged**
